# Generated by Django 6.1.1 on 2026-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="Font Awesome 6 class, e.g. 'fa-solid fa-scale-balanced'.", max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are displayed first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this practice area from the site without deleting it.')),
            ],
            options={
                'verbose_name': 'Practice Area',
                'verbose_name_plural': 'Practice Areas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
