# Generated by Django 6.1.1 on 2026-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettercampaign_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
