# Generated by Django 6.1.1 on 2026-09-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review_edit_token_review_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Used for the card, the URL, and search.', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('headline', models.CharField(help_text='The big, bold headline at the top of the article.', max_length=200)),
                ('subheadline', models.CharField(blank=True, help_text='Smaller headline shown above the body text.', max_length=200)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown on the article cards.', max_length=300)),
                ('author_name', models.CharField(blank=True, help_text='Leave blank to use the firm name.', max_length=150)),
                ('body', models.TextField(help_text='Separate paragraphs with a blank line. This gets split into pages automatically based on length.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.article')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
